¿Qué es una **matriz**?

Sabemos que es una disposición de número de forma tabular. En Python, usamos listas 2D o arreglos para representar una matriz. Una matriz siempre debe tener un valor numérico.

Lista 1D: es una lista con una fila y muchas columnas, tal como se muestra a continuación.

Lista 2D: es una lista de listas. Puede tener cualquier número de filas y columnas.


In [ ]:
# Método 1 para crear listas 1D y 2D
A = [3,2,-1,9,5]
print(A)
B =[[1,-2,3],[8,4,6],[-6,5,3]]
print(B)

[3, 2, -1, 9, 5]
[[1, -2, 3], [8, 4, 6], [-6, 5, 3]]


La biblioteca **NumPy** proporciona diferentes operaciones especializadas en matrices y proporciona operaciones más rápidas en ellas.

In [ ]:
# Método para crear matrices 1D usando NumPy

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Método 2 para crear matrices 2D usando NumPy

arr_2d =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
type(arr_2d)

#arr_3d =np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
#print(arr_3d)
#type(arr_3d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [ ]:
# Arreglo con elementos de diferentes tipos de datos

arr_2d_1 =np.array([[1,2,3],['a',5,True],[7,8,9]])
print(arr_2d_1)
type(arr_2d_1)

# ejemplo: 1 -> '1'
# a -> x
# True -> 'True'
# a -> x
# 1 + 1 == 2
# a + a == aa
# a + 1 == a1
# 3 * 2 = 6
# 3 * a = aaa

[['1' '2' '3']
 ['a' '5' 'True']
 ['7' '8' '9']]


numpy.ndarray

Accediendo a elementos de listas 2D y matrices

In [ ]:
# Accediendo a elementos de una lista 1D o matriz 1D
print(A)
print(A[1])
print(arr)
print(arr[2])


[3, 2, -1, 9, 5]
2
[1 2 3 4 5]
3


In [ ]:
# Accediendo a elementos de una matriz 2D - Método 1
print(arr_2d)
print(arr_2d[1,2])
# Accediendo a elementos de una matriz 2D - Método 2
print(arr_2d[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
2



Actualizando elementos de listas 2D

In [ ]:
# variable = 10
# print(variable)

# variable -= 2
# print(variable)

# variable = variable - 1
# print(variable)

# Para actualizar un elemento de una lista/matriz 2D
print(arr_2d)
print('----------------')
# Método 1
arr_2d[1,2]=-4
print(arr_2d)
print('----------------')
# Método 2
arr_2d[1][2]=8
print(arr_2d)


[[1 2 3]
 [4 5 8]
 [7 8 9]]
----------------
[[ 1  2  3]
 [ 4  5 -4]
 [ 7  8  9]]
----------------
[[1 2 3]
 [4 5 8]
 [7 8 9]]


Sumar/restar elementos de listas 2D

In [ ]:
a=np.array([[1,3],
            [5,4]])
b=np.array([[7,8],
            [6,9]])
rows=2
cols=2
c=np.array([[0,0],
   [0,0]])
for i in range(rows):
  for j in range(cols):
    c[i][j]=a[i][j]+b[i][j]
    # a[i][j]
    # b[i][j] +
    # c[i][j]
print(a,'\n')
print(b,'\n')
print(c)

[[1 3]
 [5 4]] 

[[7 8]
 [6 9]] 

[[ 8 11]
 [11 13]]


Multiplicar elementos de listas 2D

Multiplicación escalar

In [ ]:
b=np.array([[2,-2],
            [0,5],
            [4,7]])      # Matriz de 3x2

print(b,'\n')
n=5                      # Escalar
mul=np.zeros([3,2])
for i in range(3):
  for j in range(2):
    #print(b[i][j])
    mul[i][j]= n* b[i][j]
    #print(mul[i][j])


print(mul,'\n')

for rows in mul:
  print(rows)

[[ 2 -2]
 [ 0  5]
 [ 4  7]] 

[[ 10. -10.]
 [  0.  25.]
 [ 20.  35.]] 

[ 10. -10.]
[ 0. 25.]
[20. 35.]


In [ ]:
# Usando el método multiply()

n = 5     # Escalar

arr1= np.array([1, 2, 3])
arr2=np.multiply(arr1,n)
print(arr2)
print('---------------------')

arr3= np.array([[1, 2],
                [3, 4]])
arr4=np.multiply(arr3,n)
print(arr4)
print('---------------------')

print(a)
e=np.multiply(a,n)
print(e)

[ 5 10 15]
---------------------
[[ 5 10]
 [15 20]]
---------------------
[[1 3]
 [5 4]]
[[ 5 15]
 [25 20]]


In [ ]:
# Actividad adicional
# Para multiplicar elementos de listas/matrices 2D

a=np.array([[2,3,-4],
             [6,1,0],
             [8,9,3]])    # Matriz de 3x3

b=np.array([[2,-2],     #4+0+-16=-12  -4+15+-28
            [0,5],
            [4,7]])      # Matriz de 3x2

c= np.zeros([3,2])

print(c,'\n')
rows_a=3
cols_a=rows_b=2
cols_b=3

for i in range(3):
  for j in range(2):
    for k in range(3):
      c[i][j]=c[i][j]+a[i][k]*b[k][j]
      #print(c[i][j])


for rows in c:
  print(rows)

[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[-12. -17.]
[12. -7.]
[28. 50.]
